02_laboratorio/01_ambiente_de_prueba/projectos/prj01/app01/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('new-depa/', views.NewDepartamentoFormView.as_view()),
	
]

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/app02/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views

# uso de  nombre de dominio
app_name = "persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name= "home"),
    path(
            'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name = "empleados_todos"
        
        ),
    path(
            'empleados-admin/', 
        views.ListAllEmpleadosAdmin.as_view(),
        name = "empleados_admin"
        
        ),
    path('listar-por-area/<short_name>/', views.ListAllByAreaEmpleado.as_view()),
    path('buscar-empleado/', views.ListaEmpleadoByKword.as_view()),
    path('habilidades/<empleado>', views.ListaHabilidadesByEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmleadoDetailView.as_view(),
        name = "empleado_por_id"
        ),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name = "agregar_empleado"),
    path('success/', views.SuccessView.as_view(), name = "correcto"),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name = "modificar_empleado"),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name = "borrar_empleado"),
	
]

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/prj01/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
	re_path('', include('app01.urls')),
    re_path('polls/', include('polls.urls')),
    re_path('', include('app02.urls')),
    re_path('', include('laboratorio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/app02/models.py
from django.db import models
import os
directorio = os.getcwd()
print("#"*30, directorio)
# hola
from app01.models import Departamento

from ckeditor.fields import RichTextField

# Create your models here.

class Habilidades(models.Model):
    habilidades = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = "habilidad"
        verbose_name_plural = "habilidades de empleados"

    def __str__(self):
        return str(self.id) + " - " + self.habilidades


class Empleado(models.Model):
    """ Modelo para tabla empleado"""
    
    JOB_CHOICES = (
            ('0', "Contador"    ),
            ('1', "Administrador"   ),
            ('3', "Economista"  ),
            ('4', "Otro"    ),
        )
    
    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to = "empleado", blank=True, null = True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vid = RichTextField()
    
    def __str__(self):
        strJob = "no hay"
        for eleccion in self.JOB_CHOICES:
            if eleccion[0] == self.job:
                strJob = eleccion[1]
        #return str(self.first_name) + " " + str(self.last_name) + " [" + str(strJob) + "] - " +  str(self.departamento.short_name)
        return "= " + str(self.id) + " " + str(self.full_name) + " [" + str(strJob) + "] - " +  str(self.departamento.short_name)
        

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/app02/views.py
import pdb

from django.shortcuts import render
from django.db.models import Q
from django.urls import reverse_lazy

from django.views.generic import (
                            ListView, 
                            DetailView,
                            CreateView,
                            TemplateView,
                            UpdateView,
                            DeleteView)


# Create your views here.

from .models import Empleado

class ListAllEmpleados(ListView):
    template_name = 'app02/lista_all.html'
    paginate_by = 4
    #ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self): 
        palabra_clave = self.request.GET.get("kword")        
        
        if palabra_clave != "" and palabra_clave is not None :
            lista = Empleado.objects.filter(
                Q(first_name__icontains = palabra_clave) |
                Q(last_name__icontains = palabra_clave) |
                Q(departamento__name__icontains = palabra_clave) 
            ).order_by('first_name')
        else:
            lista = Empleado.objects.all().order_by('first_name')
        return lista
    
class ListAllEmpleadosAdmin(ListView):
    template_name = 'app02/lista_admin.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

    
class ListAllByAreaEmpleado(ListView):
    """ Lista Empleados de un área """
    template_name = 'app02/lista_area.html'

    def get_queryset(self):
        area = self.kwargs['short_name']
        lista = Empleado.objects.filter(
        departamento__short_name = area
        )
        return lista
    

class ListaEmpleadoByKword(ListView):
    template_name = "app02/by_kword.html"
    paginate_by = 4
    context_object_name = 'empleados'

    def get_queryset(self): 
        palabra_clave = self.request.GET.get("kword")
        if palabra_clave != "":
            lista = Empleado.objects.filter(
                first_name = palabra_clave
            )
        else:
            lista = Empleado.objects.all()
        return lista
        


class ListaHabilidadesByEmpleado(ListView):
    template_name = "app02/habilidades.html"    
    context_object_name = 'habilidades'

    def get_queryset(self): 
        id = self.kwargs['empleado']
        empleado = Empleado.objects.get(id=id)
        lista = [empleado, empleado.habilidades.all()]
        return lista
        
class EmleadoDetailView(DetailView):
    model = Empleado
    template_name = "app02/empleado_detail.html"

    def get_context_data(self, **kwargs):
        context = super(EmleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = "Empleado del mes"
        return context

class SuccessView(TemplateView):
    template_name = "app02/success.html"

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "app02/add.html"    
    fields = [  "first_name",
                "last_name",
                "job",
                "avatar",
                "departamento",
                "habilidades"]    
    success_url = reverse_lazy("persona_app:empleados_admin")

    def form_valid(self, form):        
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + " " + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)

    
class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "app02/update.html"
    fields = [
        'id',
        'first_name',
        'last_name',
        'job',
        'avatar',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy("persona_app:empleados_admin")

    def form_valid(self, form):        
        print("*"*40, "form_valid")
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + " " + empleado.last_name
        empleado.save()
        return super(EmpleadoUpdateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        print("*"*40, "POST")
        self.object = self.get_object()
        print(request.POST)
        print(request.POST['last_name'])
        request.POST._mutable = True
        request.POST['last_name'] = "mutable"
        request.POST._mutable = False
        return super().post(request, *args, **kwargs)
        

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "app02/delete.html"
    success_url = reverse_lazy("persona_app:empleados_admin")


class InicioView(TemplateView):
    template_name = 'inicio.html'

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/add.html
{% extends 'base.html' %}

{% block title %} Agregar Empledo {% endblock title %}

{% block content%}    

    {% include 'include/header.html'%}
    
    <div class = "grid-container">
        <form class = "grid-x  grid-margin-x cell medium-5" method="POST" enctype="multipart/form-data" action = "">
            <h1 class = "cell">Agregar un nuevo Empleado</h1>
            {% csrf_token %}
            <div class = "cell large-6">
                <label>Nombres{{form.first_name}}</label>
            </div>
            <div class = "cell large-6">
                <label>Apellidos{{form.last_name}}</label>
            </div>
            <div class = "cell large-6">
                <label>Trabajo{{form.job}}</label>
            </div>
            <div class = "cell large-6">
                <label>Departamento{{form.departamento}}</label>
            </div>
            <div class = "cell large-6">
                <label>Habilidades{{form.habilidades}}</label>
            </div>
            <div class = "cell large-6">
                <label>Avatar{{form.avatar}}</label>
            </div>
            <p/>
            <div class = "cell large-12">
                <button class = "success button" type = "submit">Enviar</button>
            </div>                        
        </form>
    </div>

{% endblock content%}    

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/by_kword.html
<h1>Buscar Empleados</h1>


<form method="GET">
	{% csrf_token %}
	<input type="text" id = "kword" name = "kword" 
    placeholder = "ingrese nombre"/>
    <button type="submit">Buscar</button>
    
</form>
   
<h2> Lista de Resultados</h2>

{%for e in empleados%}
	
    <li>{{e}}</li>

{%endfor%}

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/delete.html
{%extends 'base.html'%}

{% block title %} {% endblock title %}

{% block content%}    

{% include 'include/header.html' %}
<h2>Confirmación de Borrado</h2>
<h3>Empleado: {{ object.full_name }}</h3>

<form method="POST">
    {%csrf_token%}
    <button class = "button alert" type = "submit">Borrar</button>
</form>

{% endblock content%}   

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/empleado_detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Detalle {% endblock title %}

{% block content%}    

    {% include 'include/header.html'%}

    <div class = "grid-container">
        <div class = "gird-x grid-margin-x align-center">
            <div class="cell card large-4" style="width: 300px;">
                <div class="card-divider">
                    {{object.get_job_display}}
                </div>
                {% if object.avatar %}
                    <img src="{{object.avatar.url}}">
                {% else %}
                    <img src="{% static 'img/inicio/ruleta/01.jpg' %}">
                {% endif %}

                
                <div class="card-section">
                  <h4>{{empleado.full_name}}</h4>
                  <p>{{empleado.departamento.short_name}}</p>
                  <p><span class = "label">Habilidades</span></p>
                  <ul class = "vertical menu">
                  {% for h in empleado.habilidades.all %}
                    <li>{{h.habilidades}}</li>
                  {% endfor %}
                  </ul>
                </div>
              </div>
        </div>
    </div>
    
{% endblock content%}




<div class = "grid-container">    
    <h1>Empleado  <h1>
    <h2 >Detalle {{titulo}}</h2>
    
    <div class = "grid-x">
        <div class = "cell large-6">
            <label>Nombres: {{object.first_name}}</label>
        </div>
        <div class = "cell large-6">
            <label>Apellidos: {{object.last_name}}</label>
        </div>
        <div class = "cell large-6">
            <label>Trabajo: {{object.job}}</label>
        </div>
        <div class = "cell large-12">
            <label>Departamento: {{object.departamento}}</label>
        </div>
        <div class = "cell large-12">
            <label>Habilidades: {{object.habilidades}}</label>
        </div>
    </div>
</div>

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/habilidades.html
<h1>Habilidades</h1>

   
<h2> Lista de Resultados</h2>
Nombre : <br>
{{habilidades.0}}

<p>
Habilidades: 
{%for h in habilidades.1%}
	
    <li>{{h}}</li>

{%endfor%}

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/lista_admin.html
{% extends 'base.html' %}

{% block title %} Lista de Empleados Admin{% endblock title %}


{% load static %}



{% block content%}    

{% include 'include/header.html'%}


<div class = "grid-x">
  <div class = "cell">
    <a class="button primary" href="{% url 'persona_app:agregar_empleado' %}">Agregar Empleado</a>
  </div>
    <div class = "cell">
        
        <table>
            <thead>
              <tr>
                <th width="200">ID</th>
                <th>Nombre</th>
                <th width="150">Apellidos</th>
                <th width="150">Completo</th>
                <th width="150">Departamento</th>
                <th width="150">Acción</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for e in empleados %}
    	        <tr>
                <td>{{e.id}}</td>
                <td>{{e.first_name}}</td>
                <td>{{e.last_name}}</td>
                <td>{{e.full_name}}</td>
                <td>{{e.departamento}}</td>
                <td><a class="button Primary" href={% url 'persona_app:modificar_empleado' e.id %}>Editar</a></td>
                <td><a class="button Alert" href={% url 'persona_app:borrar_empleado' e.id %}>Borrar</a></td>
                </tr>                
            
                {%endfor%}
                
              
            </tbody>
          </table>
   
    </div>
    <div class = "cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="pagination-previous">
              <a href = "?page={{page_obj.previous_page_number}}">Atras</a>
            <span class="show-for-sr">page</span></li>          
          {% endif %}
          {% for pagina in paginator.page_range %}
            {% ifequal pagina page_obj.number %}              
              <li class="current"><span class="show-for-sr"></span> 
                <a href="?page={{pagina}}" aria-label="Page">{{pagina}}</a>
              </li>
            {% else %} 
              <li><a href="?page={{pagina}}" aria-label="Page">{{pagina}}</a></li>
            {% endifequal %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
            {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
</div>    



{% endblock content%}  

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/lista_all.html
{% extends 'base.html' %}

{% block title %} Lista de Empleados {% endblock title %}


{% load static %}



{% block content%}    

{% include 'include/header.html'%}


<div class = "grid-x">
    <div class = "cell">Lista de Empleados</div>
    <form class = "grid-x cell grid-margin-x" method="GET" >
        {%csrf_token%}
        <div class = "cell large-7 medium-7 ">
            <input id = "kword" name = "kword" type="text" placeholder="Buscar Empleado"/>
        </div>
        <div class = "cell large-3 medium-3 ">
            <button type = "submit" class="button success" href="#">Buscar</button>
        </div>    
    </form>
    <div class = "cell">
        
        <table>
            <thead>
              <tr>
                <th width="200">ID</th>
                <th>Nombre</th>
                <th width="150">Apellidos</th>
                <th width="150">Completo</th>
                <th width="150">Departamento</th>
                <th width="150">Acción</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for e in empleados %}
    	        <tr>
                <td>{{e.id}}</td>
                <td>{{e.first_name}}</td>
                <td>{{e.last_name}}</td>
                <td>{{e.full_name}}</td>
                <td>{{e.departamento}}</td>
                <td><a class="button success" href={% url 'persona_app:empleado_por_id' e.id %}>Acción</a></td>
                </tr>                
            
                {%endfor%}
                
              
            </tbody>
          </table>
   
    </div>
    <div class = "cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="pagination-previous">
              <a href = "?page={{page_obj.previous_page_number}}">Atras</a>
            <span class="show-for-sr">page</span></li>          
          {% endif %}
          {% for pagina in paginator.page_range %}
            {% ifequal pagina page_obj.number %}              
              <li class="current"><span class="show-for-sr"></span> 
                <a href="?page={{pagina}}" aria-label="Page">{{pagina}}</a>
              </li>
            {% else %} 
              <li><a href="?page={{pagina}}" aria-label="Page">{{pagina}}</a></li>
            {% endifequal %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
            {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
</div>    



{% endblock content%}  

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/lista_area.html
<h1>Todos los Empleados de un área</h1>
{{object_list }}

<ul>
	{% for e in object_list %}
    	
        <li>{{e}}</li>
    
    {%endfor%}
</ul>

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/success.html
{% extends 'base.html'%}



{% block title %} Exito{% endblock title %}

{% block content%}    

    {% include 'include/header.html' %}
    <h1>Acción Realizada Correctamente</h1>

{% endblock content%}    

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/templates/app02/update.html
{% extends 'base.html'%}

{% block title %} Modificar Empleado {% endblock title %}


{% block content%}    

{% include 'include/header.html'%}
        

<form class = "grid-container" method="POST" enctype="multipart/form-data"> 
    <h1>Modificando el Emplado.</h1>
    {%csrf_token%}
    <div class = "grid-x grid-margin-x ">
        <div class = "cell large-6">
            <label>Nombres : 
                {{form.first_name}}
            </label>
        </div>
        <div class = "cell large-6">
            <label>Apellidos : 
                {{form.last_name}}
            </label>
        </div>        
        <div class = "cell large-6">
            <label>Trabajo : 
                {{form.job}}
            </label>
        </div>        
        <div class = "cell large-6">
            <label>Departamento : 
                {{form.departamento}}
            </label>
        </div>        
        <div class = "cell large-6 medium-12 small-12">
            <label>Habilidades : 
                {{form.habilidades}}
            </label>
        </div>   
        <div class = "cell large-6 medium-12 small-12">
            <label>Avatar : 
                {{form.avatar}}
            </label>
        </div>       
    </div>
    <button class = "button" type = "submit">Guardar</button>
</form>

{% endblock content%}   