02_laboratorio/01_ambiente_de_prueba/projectos/prj01/app01/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('new-depa/', views.NewDepartamentoFormView.as_view()),
	
]

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

"""
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
"""

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/prj01/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
	re_path('', include('app01.urls')),
    re_path('polls/', include('polls.urls')),
    re_path('', include('app02.urls')),
    re_path('', include('laboratorio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/polls/models.py
import datetime 

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text + "-" + str(self.pub_date)

    def was_published_recently(self):
        now = timezone.now()
        #return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):        
        return "[ " + self.question.question_text + " ]  = " + self.choice_text 

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/polls/views.py
from django.http import (
        HttpResponse, 
        Http404,
        HttpResponseRedirect
)

from django.shortcuts import render, get_object_or_404

from django.urls import reverse

from django.db.models import F

from django.views import generic

from django.utils import timezone

from .models import (
                Question as Q, 
                Choice as C
)

# Create your views here.

def index(request):    
    print(" # "*30, timezone.now())
    last_question = Q.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')[:5]    
    context = {'latest_question_list' : last_question}
    return render(request, 'polls/index.html', context)    

def detail(request, question_id):    
    q = get_object_or_404(Q, pk =question_id)    
    context = {'question':q}
    return render(request, 'polls/detail.html', context)    

def results(request, question_id):
    q = get_object_or_404(Q, pk=question_id)
    context = {'question':q}
    return render(request, 'polls/results.html', context)

def vote(request, question_id):
    q = get_object_or_404(Q, pk=question_id)
    try:
        selected_choice = q.choice_set.get(pk=request.POST['choice'])
    except(keyError, C.DoesNotExist):
        context = {
                'question':q, 
                'error_message': 'You didnt select a choice'
        }
        return render(request, 'polls/detail.html', context)
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(q.id,)))


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):        
        return Q.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')[:5]
        
        
    

class DetailView(generic.DetailView):
    model = Q
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Q
    template_name = 'polls/results.html'

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Pregunta ver A01</title>
  </head>
  <body>
    <h1>{{ question }}</h1>

    {% if error_message %}<p><strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">

        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type = "radio" name = "choice" id = "choice
            {{ forloop.counter}}" value = "{{ choice.id}}">

            <label for ="choice{{ forloop.counter }}">
                {{choice.choice_text}}</label><br>
        {% endfor %}
        <input type = "submit" value = "Vote">
    </form>

    
  </body>
</html>

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index ver A01</title>
  </head>
  <body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
  </body>
</html>

02_laboratorio/01_ambiente_de_prueba/projectos/prj01/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index ver A01</title>
  </head>
  <body>
    {% if question %}
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} - {{choice.votes}} voto{{choice.votes|pluralize}} </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No existe esta pregunta.</p>
{% endif %}

<a href="{% url 'polls:detail' question.id  %}"> Votas otra vez?</a>

  </body>
</html>