05_proyectos/myblog/blog/applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),
    path(
        'entrada/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entry-detalle',
    ),
]

05_proyectos/myblog/blog/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='plantilla',
    ),  
    path(
        'registro-suscripcion', 
        views.SuscritorCreateViewCreateView.as_view(),
        name='add-suscriptor',
    ),  
    path(
        'contacto', 
        views.ContactoCreateView.as_view(),
        name='add-contacto',
    ),
]

05_proyectos/myblog/blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

05_proyectos/myblog/blog/applications/home/models.py
from django.db import models

# Create your models here.

from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    """ Home """

    title = models.CharField(
            'nombre', 
            max_length=50
    )    
    description = models.TextField()
    about_title = models.CharField(
            'Titulo Nosotros',
             max_length=50
    )
    about_text = models.TextField()
    contact_email = models.EmailField(
            'email de contacto', 
            blank=True,
            null=True
    )    
    phone = models.CharField(
        'Teléfono contacto', 
        max_length=20
    )

    class Meta:
        verbose_name = 'Pagina Principal'
        verbose_name_plural = 'Pagina Principal'

    def __str__(self):
        return self.title


class Suscribers(TimeStampedModel):
    """ Suscriptor """

    email = models.EmailField()

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

    def __str__(self):
        return self.email


class Contact(TimeStampedModel):
    """ Contacto """

    full_name = models.CharField(
            'Nombres', 
            max_length=60
    )

    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

    def __str__(self):
        return self.full_name

05_proyectos/myblog/blog/applications/home/forms.py
from django import forms


from .models import Suscribers, Contact

class SuscribersForm(forms.ModelForm):
    class Meta:
        model = Suscribers        
        fields = (
            'email',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder':'Correo Electrónico ...',
                }
            )
        }

class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contact        
        fields = ('__all__')
            

05_proyectos/myblog/blog/applications/home/views.py
import datetime
#
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import (
    TemplateView,
    CreateView
)
# apps
from applications.entrada.models import Entry
from applications.home.models import Home

# forms
from . import forms

class HomePageView(TemplateView):
    template_name = "home/index.html"

    
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        # contexto de portada
        context["portada"] = Entry.objects.entrada_en_portada()
        context["portadas"] = Entry.objects.entradas_en_portada()
        context["ultimas_entradas"] = Entry.objects.ultimas_entradas()
        context['home'] = Home.objects.latest('created')
        context['form'] = forms.SuscribersForm

        """ con = context["portadas"]
        import pdb
        pdb.set_trace() """
        return context
    


class SuscritorCreateViewCreateView(CreateView):
    form_class = forms.SuscribersForm
    success_url = '.'


class ContactoCreateView(CreateView):
    form_class = forms.ContactoForm
    success_url = '.'

05_proyectos/myblog/blog/templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

05_proyectos/myblog/blog/templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{ portada.image.url }}">
                <div class="card-section">
                  <h4><a href = {%url 'entrada_app:entry-detalle' portada.id %}> 
                        {{ portada.title }}
                    </a> 
                    </h4>
                  <p>{{ portada.resume}}</p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">
        {%for por in portadas%}            
        
            <div class="cell small-12 large-6">
                <div class="card" style="width: 100%;">
                    <img src="{{ por.image.url }}" style = "height: 120px; width: 50%;">
                    <div class="card-section">
                      <h5>
                        <a href = {%url 'entrada_app:entry-detalle' por.id %}> 
                            {{por.title}}
                        </a> 
                      </h5>
                    </div>
                </div>
            </div>
        
        <!-- FIN bloque de blog principal -->
        {%endfor%}
        </div>
        
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h5>Conoce mas de nostros:</h5>
            <p>
                {{home.about_text}}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="POST" action = "{%url 'home_app:add-suscriptor'%}">{%csrf_token%}
                    <div class="cell small-12">
                        {{form.as_p}}
                    </div>
                    <div class="cell small-12">
                        <button type = "submit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->    
    <div class="grid-x grid-margin-x align-center">        
        <h3 class="cell">Articulos Recientes:</h3>
        {%for ult_entrada in ultimas_entradas%}  
        <div class="cell small-6 large-4">
            <div class="card" style="width: 100%;">
                <img src="{{ult_entrada.image.url}}">
                <div class="card-section">
                  <h4>
                    <a href = {%url 'entrada_app:entry-detalle' ult_entrada.id %}> 
                        {{ ult_entrada.title }}
                    </a> 
                  </h4>
                  <p>{{ult_entrada.resume | truncatechars:100}}</p>
                </div>
            </div>
        </div>
        {%endfor%}  
        
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}