05_proyectos/myblog/blog/applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),
    path(
        'entrada/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entry-detalle',
    ),
]

05_proyectos/myblog/blog/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='plantilla',
    ),  
    path(
        'registro-suscripcion', 
        views.SuscritorCreateViewCreateView.as_view(),
        name='add-suscriptor',
    ),  
    path(
        'contacto', 
        views.ContactoCreateView.as_view(),
        name='add-contacto',
    ),
]

05_proyectos/myblog/blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

05_proyectos/myblog/blog/templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" method="POST" action="{% url 'home_app:add-contacto' %}">
          {%csrf_token%}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombres
                    <input type="text" placeholder="nombres..." name = "full_name" id = "id_full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="email" placeholder="Correo ..." name = "email" id = "id_email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje"  name = "message" id = "id_message" ></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Enviar</button>
                </div>
            </div>
        </form>
    </div>
</div>





<div class="grid-x grid-margin-x">
  <div class="cell auto"></div>
  <div class="cell large-4">
    <span class="label warning"><i class="fi-x"></i> {{correo}}</span>
    <span class="label"><i class="fi-widget"></i> {{phone}}</span>
  </div>
  <div class="cell auto"></div>
</div>

05_proyectos/myblog/blog/templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="#" style="font-size: 20px; color: #0277bd;">
                Neunapp Blog
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="{%url 'home_app:plantilla' %}">Home</a>
                </li>
                <li>
                    <a href="{%url 'entrada_app:entry-lista'%}">Blog</a>
                </li>
                <li>
                    <a class="success button">Acceder</a>
                </li>
                
            </ul>
        </div>
    </div>
</header>